[package]
name = "osu-markov"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.47.0"
tokio = "1"
rusqlite = "0.32.0"
rand = "0.8.5"
twitter-v2 = "0.1.8"
futures = "0.3.30"
