name: Linux Build

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build for Linux
              run: cargo build -r --verbose

            - name: Run tests
              run: cargo test --verbose

            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: osu-markov_x86_64
                  path: target/release/osu-markov
